### ISSUE TITLE
Demos Needed

### ISSUE THREAD

**Issue by AngelicTech** [TurboPack/LockBox3#11]
Demos of how to use Lockbox 3 programmatically are needed.

**Comment by SeanBDurkin** [comment]
http://lockbox.seanbdurkin.id.au/LB3Help_Home

**Comment by Jarru8** [comment]
> http://lockbox.seanbdurkin.id.au/LB3Help_Home

Forbidden
You don't have permission to access this resource.

Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request. 😢

**Comment by M0nsieurT** [comment]
> http://lockbox.seanbdurkin.id.au/LB3Help_Home

The demo link does not match with unit names on this repository. Do someone have a real demo working with this one ?

**Comment by romankassebaum** [comment]
That's all we have.
