### ISSUE TITLE
[bcc32 Error] uTPLb_CryptographicLibrary.hpp(174): Simple type name expected

### ISSUE THREAD

**Issue by joeyshuey** [TurboPack/LockBox3#16]
Hello. I am trying to use LockBox 3.7, which I installed via GetIt on RAD Studio 10.4 with one of my C++ Builder projects. 
When building I get "[bcc32 Error] uTPLb_CryptographicLibrary.hpp(174): Simple type name expected"
With the line being
`__property TOnGenerateKeyFunc OnCustomCipherGenerateKey = {read=FOnGenerateKeyFunc, write=FOnGenerateKeyFunc};`

**Comment by AnDy01111** [comment]
I have the same problem, but only if the classic Borland compiler was selected in the project options.

**Comment by romankassebaum** [comment]
I have no idea.

**Comment by tracer1808** [comment]
Please unselect "Classic Borland Compiler" option in packages by default here, as it produces compilation errors if packages are to be compiled manually. Not many people (especially students) will know how to handle this.

**Comment by romankassebaum** [comment]
Done.
