### ISSUE TITLE
C++ Builder Community Edition (10.3.3) Installation fail

### ISSUE THREAD

**Issue by ElmarBaumann66** [TurboPack/LockBox3#18]
Hello, is there a possibility to install your Components to the C++ Builder Community Edition ?

I would try the Encrypt/Decrypt Functionallity in one of my Projects.

I see two Versions in the GetIT Manager (2,4 and 3.7) so what do i have to install ?

Version 2.4
Installation installing without THash,TCryptographicLibraray etc - just the Encrypt/Decprypt Method Components.

Version 3.7
Installation installing  just THash,TCryptographicLibraray (4 Components) and no Encrypt/Decrypt Method Components - and there is a Error-Message at the Beginning of the Installation (Script-Error).
There is a Error-Message if i try to place a Component on a Form (Not possible in this Module . . .) 

cheers

Elmar Baumann

**Comment by romankassebaum** [comment]
C++Builder Community Edition should work.
LockBox is the original version from TurboPower, LockBox3 has been designed by Sean B Durkin (http://www.lockbox.seanbdurkin.id.au).

You should use both libraries only in legacy code, not for new projects. If you have question to LockBox3 you should ask Sean.

**Comment by SeanBDurkin** [comment]
Hi All,

I seem to be missing some context here.

What is the original problem/question, and who is asking?


Faithfully,
Sean B. Durkin
