### ISSUE TITLE
Documentation / Examples?

### ISSUE THREAD

**Issue by Aggie85** [TurboPack/LockBox3#19]
Howdy!

I am new to LockBox3 and don't see any documentation or examples (preferably in C++).

Does any such things exist?

Thanks,

Shane

**Comment by romankassebaum** [comment]
LockBox3 should only be used in legacy projects. For new projects use commercial libraries like TMS Crypto Pack or the StreamSec components.

**Comment by Aggie85** [comment]
Thank you.

Have a great weekend.

⁣Get BlueMail for Android ​
