### ISSUE TITLE
iOS SHA1 Integer Overflow

### ISSUE THREAD

**Issue by SIG89** [TurboPack/LockBox3#22]
Hi there,

I recently switched my projects form D10 to D11. On Android everything is working fine so far. On iOS I'm getting a Integer Overflow using sha1.pas unit while using a dycrpt function. Hopefully you are able to fix this bug soon.

**Comment by romankassebaum** [comment]
Without test project this is very difficult to fix. But I noticed that LongWords are used which are an UInt64 under iOS and a UInt32 under Windows. That's why I replaced all LongWords with a UInt32. Please try again.

**Comment by SIG89** [comment]
Found the same Problem for Android, but your solutions seems to work. Will test iOS asap. But first thank you for the quick repsond!
