### ISSUE TITLE
Passphrase doesn't work with TLbRijndael

### ISSUE THREAD

**Issue by 78Mahdi** [TurboPack/LockBox3#25]
Hello

I found issue with TLbRijndael, the passphrase has no effect, but it works with TLbBlowfish, i would add the following sample

`procedure TForm1.Button1Click(Sender: TObject);
var
  ALbRijndael: TLbRijndael;
begin
 ALbRijndael := TLbRijndael.Create(nil);
 try
 ALbRijndael.GenerateKey('aaa');
 ALbRijndael.Encoding := TEncoding.UTF8;
 Memo2.Text := ALbRijndael.EncryptString(Memo1.Text);
 finally
   ALbRijndael.Free;
 end;
end;

procedure TForm1.Button2Click(Sender: TObject);
var
  ALbRijndael: TLbRijndael;
begin
 ALbRijndael := TLbRijndael.Create(nil);
 try
 ALbRijndael.GenerateKey('bbb');
 ALbRijndael.Encoding := TEncoding.UTF8;
 Memo3.Text := ALbRijndael.DecryptString(Memo2.Text);
 finally
   ALbRijndael.Free;
 end;
end;`

**Comment by romankassebaum** [comment]
I'm really not a LockBox specialist, but from what I have seen you have to set the KeySize first to ks128, ks192 or ks256. Then you can generate a key with the matching length.

**Comment by 78Mahdi** [comment]
> I'm really not a LockBox specialist, but from what I have seen you have to set the KeySize first to ks128, ks192 or ks256. Then you can generate a key with the matching length.

That's correct, thank you for response
