### ISSUE TITLE
Components Missing In Component Palette (Delphi 10.4.2 27.0.40680.4203)

### ISSUE THREAD

**Issue by stackerliew** [TurboPack/LockBox3#28]
Unable To Locate LockBox In Component Palette After Installed LockBox3.

**Comment by hannesgaenser** [comment]
Same problem in Delphi 12, Package is installed and when I click "components" Delphi shows, that the components are installed. But they are still not visible in Component palette.

**Comment by romankassebaum** [comment]
The problem is that you cannot install the Vcl and the FMX version at the same time.

**Comment by hannesgaenser** [comment]
Thx for the answer, though would be good in future if it could be used in both frameworks.
