### ISSUE TITLE
TCodec.DecryptStream compatibility

### ISSUE THREAD

**Issue by guetin** [TurboPack/LockBox3#4]
Previously I was using SeanBDurkin/tplockbox 3.6.3.0. I installed the Delphi 10 Seattle LockBox 3.5.0 package from IDE GetIt and I cannot get my previous crypted files to be decrypted with TCodec.DecryptStream. Are the two versions compatibles ? Here is my components configuration :

object Codec1: TCodec
AsymetricKeySizeInBits = 1024
AdvancedOptions2 = []
CryptoLibrary = CryptographicLibrary1
Left = 616
Top = 24
StreamCipherId = 'native.StreamToBlock'
BlockCipherId = 'native.3DES.1'
ChainId = 'native.CBC'
end
object CryptographicLibrary1: TCryptographicLibrary
Left = 624
Top = 88
end

Thanks

**Comment by romankassebaum** [comment]
Again, you should ask Sean directly.

**Comment by leocecchet** [comment]
Hello.
I have a similar problem, but I use the EncryptString and DecryptString methods.
I used a version of the component in Delphi XE7 and had created a dll to share the encryption in several programs.
However, with the current version (Delphi RIO) the previously generated encryption does not decrypt in the current one, and vice versa.
What should I do?
@guetin , did you solve the problem?
@romankassebaum How do I contact @SeanBDurkin ?

**Comment by romankassebaum** [comment]
You can find him here: http://www.lockbox.seanbdurkin.id.au/.
