### ISSUE TITLE
No Visual Components

### ISSUE THREAD

**Issue by Private-Storm** [TurboPack/LockBox3#6]
Is that correct that there are "no" components installed inside XE10 or XE8 IDE? (It tells me that the package is installed(no errors raised) which I can confirm but no components in the component palette nor a Lockbox entry can be found, so I only can use Lockbox non visually.)
I've already followed the installation process more then once but can't get it working no matter what I've tried.

**Comment by romankassebaum** [comment]
No, there must be components like THash, TCodec, TCryptographicLibrary and TSignatory.
