### ISSUE TITLE
LockBox3 visual components missing

### ISSUE THREAD

**Issue by sstillwell** [TurboPack/LockBox3#8]
In issue #6 I believe your answer was unclear - after installing LockBox3 and restarting the IDE, should there be any visual components in the palette?

I've followed instructions to add the 'run' source folder and all subfolders to the library search path, opened the package group and have done a build all in the projects, and have installed the packages.  The install succeeds, but no components are listed as installed in the success dialog.  The packages DO show up and are enabled in the Component > Install Packages... dialog.

This is in Delphi 'Berlin' 10.1.

**Comment by romankassebaum** [comment]
The problem was the '.' in the name of the register unit. I fixed it.
